#!/usr/bin/env bash
# Regenerate be/nfcxx_names.h from the EDG sources: name tables for the IL enumerations the Path B back end
# prints (operator, expression-node, statement and dynamic-init kinds). EDG has no shared name tables for
# these in this configuration, so each enumerator becomes one case in a switch. A switch fails to compile
# if an enumerator is missing, and enumerators compiled out in the configured build are removed by hand
# (see the note in the generated header). Aliases ("NAME = OTHER") are skipped so case labels stay unique.
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
il=$root/3rd/edg/src/il_def.h
out=$root/be/nfcxx_names.h

# names_of <enum-tag> <prefix>: enumerators of "enum <enum-tag>" that have the given prefix.
names_of() {
  local start; start=$(grep -n "^enum $1 " "$il" | head -1 | cut -d: -f1)
  awk -v s="$start" -v pre="$2" 'NR>s && /^};/ {exit}
    NR>s && $0 ~ "^[ \t]*"pre"[a-z_0-9]+[ \t]*," { sub(/^[ \t]*/,""); sub(/[ \t]*,.*/,""); print }' "$il"
}

# Enumerators that EDG compiles out with the cpfe configuration in scripts/setup-pathb.sh
# (DO_IL_LOWERING and friends); a case label for them would not compile.
skip=$(mktemp)
trap 'rm -f "$skip"' EXIT
printf '%s\n' enk_lowered_eh_construct ck_stack_offset > "$skip"

{
  echo "/* Generated by scripts/pathb-gen-names.sh from 3rd/edg/src/il_def.h. Do not edit by hand. */"
  echo "/* Enumerators compiled out in the configured build (see skip list below) are dropped. */"
  while read -r tag prefix fn ty var; do
    echo
    echo "static const char *$fn($ty $var)"
    echo "{"
    echo "  switch ($var) {"
    names_of "$tag" "$prefix" | grep -vxF -f "$skip" | while read -r n; do
      echo "    case $n: return \"${n#"$prefix"}\";"
    done
    echo "    default: return NULL;"
    echo "  }"
    echo "}"
  done <<'TABLES'
an_expr_operator_kind eok_ nfcxx_eok_name an_expr_operator_kind op
an_expr_node_kind enk_ nfcxx_enk_name an_expr_node_kind kind
a_statement_kind stmk_ nfcxx_stmk_name a_statement_kind kind
a_dynamic_init_kind dik_ nfcxx_dik_name a_dynamic_init_kind kind
a_constant_repr_kind ck_ nfcxx_ck_name a_constant_repr_kind kind
TABLES
} > "$out"
echo "wrote $out"
