/* Generated by scripts/pathb-gen-names.sh from 3rd/edg/src/il_def.h. Do not edit by hand. */
/* Enumerators compiled out in the configured build (see skip list below) are dropped. */

static const char *nfcxx_eok_name(an_expr_operator_kind op)
{
  switch (op) {
    case eok_address_of: return "address_of";
    case eok_reference_to: return "reference_to";
    case eok_handle_to: return "handle_to";
    case eok_indirect: return "indirect";
    case eok_ref_indirect: return "ref_indirect";
    case eok_cast: return "cast";
    case eok_lvalue_cast: return "lvalue_cast";
    case eok_ref_cast: return "ref_cast";
    case eok_lvalue_adjust: return "lvalue_adjust";
    case eok_class_rvalue_adjust: return "class_rvalue_adjust";
    case eok_box: return "box";
    case eok_handle_to_box: return "handle_to_box";
    case eok_unbox: return "unbox";
    case eok_unbox_lvalue: return "unbox_lvalue";
    case eok_base_class_cast: return "base_class_cast";
    case eok_derived_class_cast: return "derived_class_cast";
    case eok_pm_base_class_cast: return "pm_base_class_cast";
    case eok_pm_derived_class_cast: return "pm_derived_class_cast";
    case eok_dynamic_cast: return "dynamic_cast";
    case eok_ref_dynamic_cast: return "ref_dynamic_cast";
    case eok_bool_cast: return "bool_cast";
    case eok_array_to_pointer: return "array_to_pointer";
    case eok_dot_vacuous_destructor_call: return "dot_vacuous_destructor_call";
    case eok_points_to_vacuous_destructor_call: return "points_to_vacuous_destructor_call";
    case eok_assume: return "assume";
    case eok_noexcept: return "noexcept";
    case eok_parens: return "parens";
    case eok_negate: return "negate";
    case eok_unary_plus: return "unary_plus";
    case eok_complement: return "complement";
    case eok_not: return "not";
    case eok_vector_not: return "vector_not";
    case eok_vector_fill: return "vector_fill";
    case eok_xconj: return "xconj";
    case eok_real_part: return "real_part";
    case eok_imag_part: return "imag_part";
    case eok_post_incr: return "post_incr";
    case eok_post_decr: return "post_decr";
    case eok_pre_incr: return "pre_incr";
    case eok_pre_decr: return "pre_decr";
    case eok_add: return "add";
    case eok_subtract: return "subtract";
    case eok_multiply: return "multiply";
    case eok_divide: return "divide";
    case eok_remainder: return "remainder";
    case eok_jmultiply: return "jmultiply";
    case eok_jdivide: return "jdivide";
    case eok_fjadd: return "fjadd";
    case eok_jfadd: return "jfadd";
    case eok_fjsubtract: return "fjsubtract";
    case eok_jfsubtract: return "jfsubtract";
    case eok_padd: return "padd";
    case eok_psubtract: return "psubtract";
    case eok_pdiff: return "pdiff";
    case eok_shiftl: return "shiftl";
    case eok_shiftr: return "shiftr";
    case eok_and: return "and";
    case eok_or: return "or";
    case eok_xor: return "xor";
    case eok_eq: return "eq";
    case eok_ne: return "ne";
    case eok_gt: return "gt";
    case eok_lt: return "lt";
    case eok_ge: return "ge";
    case eok_le: return "le";
    case eok_spaceship: return "spaceship";
    case eok_vector_eq: return "vector_eq";
    case eok_vector_ne: return "vector_ne";
    case eok_vector_gt: return "vector_gt";
    case eok_vector_lt: return "vector_lt";
    case eok_vector_ge: return "vector_ge";
    case eok_vector_le: return "vector_le";
    case eok_gnu_min: return "gnu_min";
    case eok_gnu_max: return "gnu_max";
    case eok_assign: return "assign";
    case eok_add_assign: return "add_assign";
    case eok_subtract_assign: return "subtract_assign";
    case eok_multiply_assign: return "multiply_assign";
    case eok_divide_assign: return "divide_assign";
    case eok_remainder_assign: return "remainder_assign";
    case eok_shiftl_assign: return "shiftl_assign";
    case eok_shiftr_assign: return "shiftr_assign";
    case eok_and_assign: return "and_assign";
    case eok_or_assign: return "or_assign";
    case eok_xor_assign: return "xor_assign";
    case eok_padd_assign: return "padd_assign";
    case eok_psubtract_assign: return "psubtract_assign";
    case eok_bassign: return "bassign";
    case eok_land: return "land";
    case eok_lor: return "lor";
    case eok_vector_land: return "vector_land";
    case eok_vector_lor: return "vector_lor";
    case eok_comma: return "comma";
    case eok_subscript: return "subscript";
    case eok_vector_subscript: return "vector_subscript";
    case eok_dot_field: return "dot_field";
    case eok_points_to_field: return "points_to_field";
    case eok_pm_field: return "pm_field";
    case eok_pm_points_to_field: return "pm_points_to_field";
    case eok_dot_pm_func_ptr: return "dot_pm_func_ptr";
    case eok_points_to_pm_func_ptr: return "points_to_pm_func_ptr";
    case eok_dot_static: return "dot_static";
    case eok_points_to_static: return "points_to_static";
    case eok_virtual_function_ptr: return "virtual_function_ptr";
    case eok_question: return "question";
    case eok_vector_question: return "vector_question";
    case eok_call: return "call";
    case eok_dot_member_call: return "dot_member_call";
    case eok_points_to_member_call: return "points_to_member_call";
    case eok_dot_pm_call: return "dot_pm_call";
    case eok_points_to_pm_call: return "points_to_pm_call";
    case eok_cli_subscript: return "cli_subscript";
    case eok_va_start: return "va_start";
    case eok_va_arg: return "va_arg";
    case eok_va_end: return "va_end";
    case eok_va_copy: return "va_copy";
    case eok_va_start_single_operand: return "va_start_single_operand";
    case eok_lvalue: return "lvalue";
    case eok_await: return "await";
    case eok_yield: return "yield";
    case eok_splice: return "splice";
    case eok_error: return "error";
    default: return NULL;
  }
}

static const char *nfcxx_enk_name(an_expr_node_kind kind)
{
  switch (kind) {
    case enk_error: return "error";
    case enk_operation: return "operation";
    case enk_constant: return "constant";
    case enk_variable: return "variable";
    case enk_field: return "field";
    case enk_temp_init: return "temp_init";
    case enk_lambda: return "lambda";
    case enk_new_delete: return "new_delete";
    case enk_gcnew: return "gcnew";
    case enk_throw: return "throw";
    case enk_condition: return "condition";
    case enk_object_lifetime: return "object_lifetime";
    case enk_typeid: return "typeid";
    case enk_sizeof: return "sizeof";
    case enk_sizeof_pack: return "sizeof_pack";
    case enk_alignof: return "alignof";
    case enk_datasizeof: return "datasizeof";
    case enk_address_of_ellipsis: return "address_of_ellipsis";
    case enk_statement: return "statement";
    case enk_reuse_value: return "reuse_value";
    case enk_result_of_overriding_function: return "result_of_overriding_function";
    case enk_routine: return "routine";
    case enk_vla_dealloc: return "vla_dealloc";
    case enk_type_operand: return "type_operand";
    case enk_builtin_operation: return "builtin_operation";
    case enk_param_ref: return "param_ref";
    case enk_braced_init_list: return "braced_init_list";
    case enk_c11_generic: return "c11_generic";
    case enk_builtin_choose_expr: return "builtin_choose_expr";
    case enk_yield: return "yield";
    case enk_await: return "await";
    case enk_fold: return "fold";
    case enk_initializer: return "initializer";
    case enk_concept_id: return "concept_id";
    case enk_requires: return "requires";
    case enk_compound_req: return "compound_req";
    case enk_nested_req: return "nested_req";
    case enk_const_eval_deferred: return "const_eval_deferred";
    case enk_template_name: return "template_name";
    case enk_token_sequence: return "token_sequence";
    case enk_reclaimed: return "reclaimed";
    case enk_pack_index: return "pack_index";
    default: return NULL;
  }
}

static const char *nfcxx_stmk_name(a_statement_kind kind)
{
  switch (kind) {
    case stmk_expr: return "expr";
    case stmk_if: return "if";
    case stmk_constexpr_if: return "constexpr_if";
    case stmk_if_consteval: return "if_consteval";
    case stmk_if_not_consteval: return "if_not_consteval";
    case stmk_while: return "while";
    case stmk_goto: return "goto";
    case stmk_label: return "label";
    case stmk_return: return "return";
    case stmk_coroutine: return "coroutine";
    case stmk_coroutine_return: return "coroutine_return";
    case stmk_block: return "block";
    case stmk_end_test_while: return "end_test_while";
    case stmk_for: return "for";
    case stmk_range_based_for: return "range_based_for";
    case stmk_for_each: return "for_each";
    case stmk_switch_case: return "switch_case";
    case stmk_switch: return "switch";
    case stmk_init: return "init";
    case stmk_asm: return "asm";
    case stmk_asm_func_body: return "asm_func_body";
    case stmk_try_block: return "try_block";
    case stmk_microsoft_try: return "microsoft_try";
    case stmk_decl: return "decl";
    case stmk_set_vla_size: return "set_vla_size";
    case stmk_vla_decl: return "vla_decl";
    case stmk_upc_notify: return "upc_notify";
    case stmk_upc_wait: return "upc_wait";
    case stmk_upc_barrier: return "upc_barrier";
    case stmk_upc_fence: return "upc_fence";
    case stmk_upc_forall: return "upc_forall";
    case stmk_assigned_goto: return "assigned_goto";
    case stmk_empty: return "empty";
    case stmk_stmt_expr_result: return "stmt_expr_result";
    default: return NULL;
  }
}

static const char *nfcxx_dik_name(a_dynamic_init_kind kind)
{
  switch (kind) {
    case dik_none: return "none";
    case dik_zero: return "zero";
    case dik_constant: return "constant";
    case dik_expression: return "expression";
    case dik_class_result_via_ctor: return "class_result_via_ctor";
    case dik_constructor: return "constructor";
    case dik_nonconstant_aggregate: return "nonconstant_aggregate";
    case dik_bitwise_copy: return "bitwise_copy";
    default: return NULL;
  }
}

static const char *nfcxx_ck_name(a_constant_repr_kind kind)
{
  switch (kind) {
    case ck_error: return "error";
    case ck_integer: return "integer";
    case ck_fixed_point: return "fixed_point";
    case ck_string: return "string";
    case ck_float: return "float";
    case ck_complex: return "complex";
    case ck_imaginary: return "imaginary";
    case ck_address: return "address";
    case ck_ptr_to_member: return "ptr_to_member";
    case ck_label_difference: return "label_difference";
    case ck_dynamic_init: return "dynamic_init";
    case ck_aggregate: return "aggregate";
    case ck_init_repeat: return "init_repeat";
    case ck_template_param: return "template_param";
    case ck_designator: return "designator";
    case ck_upc_threads: return "upc_threads";
    case ck_upc_mythread: return "upc_mythread";
    case ck_void: return "void";
    case ck_reflection: return "reflection";
    default: return NULL;
  }
}
